### ISSUE TITLE
Не работает программа

### ISSUE THREAD

**Issue by A6pAkal7a6pA** [maxkrivich/ChatApp#10]
Шаги по воспроизведению проблемы:
1.Запустить Chat App.
2.Ввести nick собеседника, свой, подключиться у нему.

Ожидаемый результат:
Подключаемся к собеседнику

Фактический результат:
Ничего не происходит

**Comment by entick** [comment]
По факту, подключение работает в последнем релизе программы по ip, а не по нику. По-этому, либо вы не так сформулировали проблему, либо ее и вовсе нет. Если последнее, то прошу закрыть issue
