### ISSUE TITLE
Не приходят сообщения

### ISSUE THREAD

**Issue by A6pAkal7a6pA** [maxkrivich/ChatApp#11]
Шаги по воспроизведению проблемы:
1.Запустить Chat App.
2.Ввести nick собеседника, свой, подключаемся к нему.
3.Отправляем сообщение.

Ожидаемый результат:
Приходит сообщение.

Фактический результат:
Ничего не приходит

**Comment by entick** [comment]
А вот тут у меня возникает вопрос. Если по предыдущему багу, вы не можете подключиться, то и сообщения приходить не должны, так? Попробуйте отключить антивирусы и фаерволы, у нас была схожая проблема, которая заключалась в блокировке антивирусами входящих пакетов
