### ISSUE TITLE
Подключение только с ником!

### ISSUE THREAD

**Issue by A6pAkal7a6pA** [maxkrivich/ChatApp#12]
Шаги по воспроизведению проблемы:
1.Запустить Chat App.
2.Ввести ip собеседника, свой, подключаемся к нему.
3.Отправляем сообщение.

Ожидаемый результат:
Подключится к программе

Фактический результат:
Ничего не приходит

**Comment by entick** [comment]
Формулируйте воспроизведение проблемы правильно! Ничего не понятно в пункте 2. снимайте видео - делайте, что хотите, иначе в дальнейшем ваши issue будут закрываться без рассмотрения

**Comment by maxkrivich** [comment]
Черт, что Вы делаете? Ты в skpe сам с собой часто разговариваешь? По ТЗ нельзя к себе звонить!!!!!1
