### ISSUE TITLE
Нельзя переименовать ник!

### ISSUE THREAD

**Issue by A6pAkal7a6pA** [maxkrivich/ChatApp#13]
Шаги по воспроизведению проблемы:
1.Запустить Chat App.
2.Ввести тnick собеседника, свой, подключаемся к нему.
3.Дисконектимся
4. Пытаемся сменить ник
Ожидаемый результат:
Ник меняется 

Фактический результат:
Ник не меняется

**Comment by maxkrivich** [comment]
Сходи в паспортный стол!!
