### ISSUE TITLE
Невозможно осуществить подключение 

### ISSUE THREAD

**Issue by ElenVM** [maxkrivich/ChatApp#14]
Шаги по воспроизведению проблемы:
1. Запустить ChatApp.
2. Ввести locol login. 
3. Нажать Apply.
4. Ввести Remote addr.
5. Нажать Connect.

Ожидаемый результат:
Подключение и возможность дальнейшей работы с программой.

Фактический результат:
Программа зависает и не отвечает ни на какие действия.

**Comment by maxkrivich** [comment]
Странно у нас все работает. Какую версию Вы тестировали?

**Comment by ElenVM** [comment]
та, которая у вас скинута на гит

**Comment by dimalit** [comment]
Дайте угадаю - удаленный юзер был не в сети.  Там по идее должен тайм-аут срабатывать...

**Comment by maxkrivich** [comment]
Это сарая версия

**Comment by maxkrivich** [comment]
В новой вроде все норм было
