### ISSUE TITLE
Сообщение об ошибке при вводе некорректного ip

### ISSUE THREAD

**Issue by Shazex** [maxkrivich/ChatApp#16]
Шаги по воспроизведению проблемы:
1. Ввожу ник
2. Ввожу некорректный ip (любой набор символов)
3. Попытка законектится
Ожидаемый результат:
Сообщение о невозможности подключения
Фактический результат:
Этого сообщения нет

**Comment by maxkrivich** [comment]
IP какого формата?

**Comment by Shazex** [comment]
та вообще, что угодно туда ввести(любой набор символов), оно должно выводить, что это некорректно, но к сожалению этого нет

**Comment by entick** [comment]
Уже был такой issue, не актуально. Исправлено в новой версии
