### ISSUE TITLE
Очистка окна переписки

### ISSUE THREAD

**Issue by Shazex** [maxkrivich/ChatApp#17]
Шаги по воспроизведению проблемы:
1. Ввести ник и ip
2. Приконектится и отправить сообщение
3. Дисконект 
4. Коннект к другому собеседнику
Ожидаемый результат:
Полное очищение окна переписки, после нового коннекта
Фактический результат:
Все сообщения остаются, что явно мозолит глаза при общении с новым собеседником

**Comment by maxkrivich** [comment]
ТЗ есть такой пункт?

**Comment by Shazex** [comment]
Почему не добавить, это будет очень удобно

**Comment by AnastasiaKiyan** [comment]
Мы учтем Ваше замечание.

**Comment by Shazex** [comment]
Благодарю)
