### ISSUE TITLE
Отображение русского ника при принятии входящего сообщения 

### ISSUE THREAD

**Issue by Shazex** [maxkrivich/ChatApp#18]
Шаги по воспроизведению проблемы:
1. Ввести ник 
2. Ожидать пока собеседник кинет вам запрос к общению
Ожидаемый результат:
В окошке принятия входящего запроса корректное отображение русского никнейма
Фактический результат:
Кракозяблики. Могу предоставить скриншот

**Comment by maxkrivich** [comment]
Ну так это из-за кодировки!
