### ISSUE TITLE
Невозможно сменить ник после разрыва соединения

### ISSUE THREAD

**Issue by Jojorr** [maxkrivich/ChatApp#19]
Шаги для воспроизведения:
1. Ввести local login
2. Ввести remote adress
3. Нажать Connect
4. Нажать Disconnect
Ожидаемый результат:
Разрыв соединения и активация кнопки Accept
Полученный результат:
Кнопка Accept не работает, поле Local login не активно

**Comment by AnastasiaKiyan** [comment]
Насколько я понимаю,под кнопкой "Accept" подразумевается "Apply". Если это так, то данная кнопка в любом случаи становится неактивна, если уже была нажата однажды, поскольку повторное нажатие является бессмысленным.Изменение локального ника после нажатия "Apply" не предусмотрено ТЗ, его можно изменять только при повторном открытии программы.

**Comment by entick** [comment]
Исправлено, ждите новую версию
