### ISSUE TITLE
Не разрывается соединение

### ISSUE THREAD

**Issue by Jojorr** [maxkrivich/ChatApp#20]
Шаги для воспроизведения:
1. Ввести ник
2. Ввести адрес собеседника
3. Нажать Connect
3. Нажать disconnect
4. Открыть еще одно окно чата и повторить пункты 1-3 уже в нем
Ожидаемый результат:
Подключение к собеседнику
Полученный результат:
Адрес всё еще "занят"

**Comment by entick** [comment]
Исправлено, ждите новую версию.
