### ISSUE TITLE
Невозможно установить соединение

### ISSUE THREAD

**Issue by romashkorylezzz** [maxkrivich/ChatApp#21]
Шаги по воспроизведению проблемы:
1. Запустить ChatApp.
2. Ввести локальный ник. Нажать Apply. 
3. Ввести IP собеседника files.litvinov.in.ua

Ожидаемый результат:
Connected to botnick

Фактический результат:
Ничего не происходит. Через раз программа зависает

**Comment by entick** [comment]
Исправлено, ждите новую версию
