### ISSUE TITLE
Сообщения с знаками препинания. 

### ISSUE THREAD

**Issue by DimaKovalchuk** [maxkrivich/ChatApp#29]
Шаги по воспроизведению проблемы:
1. Запустить программу.
2. Подключиться к собеседнику
3. Начать диалог используя знаки препинания в предложении  

Ожидаемый результат:
Корректное принятие сообщений 

Фактический результат:
Сообщение не принимается (даже на английском языке).

**Comment by maxkrivich** [comment]
не наша проблема!
