### ISSUE TITLE
Подключение

### ISSUE THREAD

**Issue by ArturBykov** [maxkrivich/ChatApp#33]
Шаги к воспроизведению проблемы:
1. Запустить чат.
2. Заполнить поля ника, адреса собеседника(127.0.0.1)
3. Нажать кнопку Connect.
Ожидаемый результат:
Подключаемся сами к себе (и можем начать переписку) 
Фактический результат:
Ничего не происходит(не можем ввести текс и кнопка Disconnect остается заблокированной)
![untitled2](https://cloud.githubusercontent.com/assets/15671722/12004510/2bb348e8-ab67-11e5-8e77-7f05a1bcdf19.png)

**Comment by maxkrivich** [comment]
не по ТЗ
