### ISSUE TITLE
Некорректное поведение программы

### ISSUE THREAD

**Issue by dmitriydz** [maxkrivich/ChatApp#34]
Шаги воспроизведения:
1)Запускаем программу
2)Вводим свой ник
3)Жмем кнопку Apply
4)Закрываем программу 
5)На вопрос:"Do you want to close programm" жмем "No"

Ожидаемый результат:
Программа не закрывается.

Фактический результат:
Программа закрывается и при повторе действий 1, 2 и 3 появляется сообщение :"You can't open two examples of one programm".  Ярлык программы не виден на панели задач, но остается в процессах Диспетчера задач. 
![5](https://cloud.githubusercontent.com/assets/11484978/12011171/420c9552-accc-11e5-838e-f5494635f119.png)
"

**Comment by maxkrivich** [comment]
Про это уже нам писали

**Comment by dmitriydz** [comment]
Я видел тот баг. Мало того что она закрывается, ей невозможно пользоваться без снятия задачи в диспетчере задач.

**Comment by maxkrivich** [comment]
Слушай яж написал что она становится невидимой! Ясен красен что ей невозможно пользоваться
