### ISSUE TITLE
Различная реакция программы 

### ISSUE THREAD

**Issue by dmitriydz** [maxkrivich/ChatApp#35]
Шаги
1)Ввожу ник и нажимаю Apply
2)Подключаюсь к себе 127.0.0.1
3)Ввожу сообщения и отсылаю их при помощи нажатия кнопки Send как мышкой так и при нажатии Enter

Ожидание:
Одинаковый результат в работе

Реальность:
При нажатии кнопки Send мышью печатает в строке с ником.
При отправке сообщения клавишей Enter переносит сообщение на другую строку
![9](https://cloud.githubusercontent.com/assets/11484978/12011793/0f9d4bce-ace6-11e5-96e8-e10f776042dd.png)

**Comment by maxkrivich** [comment]
По ТЗ нельзя подключатся к самому себе
