### ISSUE TITLE
Смещение полей ввода и вывода сообщений

### ISSUE THREAD

**Issue by dmitriydz** [maxkrivich/ChatApp#36]
Шаги:
1)Вводим ник, подключаемся в себе 127.0.0.1
2)Вводим большое сообщение

Ожидание
Появление полосі прокрутки
Реальность
Смещение полей для ввода и вывода
![10](https://cloud.githubusercontent.com/assets/11484978/12011871/37a4b032-ace9-11e5-948f-6e3a5e81a51d.png)

**Comment by maxkrivich** [comment]
Чувак будь реалистом! Таких сообщений в реальной жизни нету
