### ISSUE TITLE
Не выводится сообщение о неработающем соединении.

### ISSUE THREAD

**Issue by ipehov** [maxkrivich/ChatApp#4]
Шаги по воспроизведению проблемы: 
1. Запустить программу
2. Ввести ник
3(2). Ввести несуществующий ip, либо ip собеседника, который оффлайн

Ожидаемый результат:
При не успешном соединении вывод оповещения по типу "could not connection"

Фактический результат:
Программа зависает на короткое время, затем отвисает. Оповещения нет.

**Comment by entick** [comment]
Вроде иcправили, проверьте

**Comment by addep7y** [comment]
jar-ник по новой качать?
