### ISSUE TITLE
Очень странный баг.

### ISSUE THREAD

**Issue by ipehov** [maxkrivich/ChatApp#5]
Шаги по воспроизведению проблемы: 
1. Запустить программу
2. Ввести ник
3. Ждать входящее подключение.
4. Отклонить входящий звонок (входящее подключение).

Ожидаемый результат:
Успешное отклонение звонка.

Фактический результат:
Соединение не отклоняется, или отклоняется но частично, нужно нажимать кнопку Disconnect, но при нажатии на эту кнопку ничего не происходит

**Comment by entick** [comment]
Проверить

**Comment by ipehov** [comment]
Могу на этот баг тоже записать видео

**Comment by entick** [comment]
Если у вас до сих пор эта проблема, то я думаю, что вы не скачали новый jar-ник, потому что она была, я исправил, и выложил новый релиз с исправлением этого бага. Теперь все в порядке должно быть
