### ISSUE TITLE
Русский ник в поле Remote Login некорректно выводится

### ISSUE THREAD

**Issue by ipehov** [maxkrivich/ChatApp#7]
Шаги по воспроизведению проблемы: 
1. Запустить программу
2. Ввести ник.
3. Подключиться к собеседнику, у которого ник написан русскими символами

Ожидаемый результат:
Корректное отображение ника в поле Remote Login

Фактический результат:
Некорректное отображение ника в поле Remote Login =D

**Comment by entick** [comment]
По идеи он и должен некорректно выводитьcя, потому что в протоколе чата четко напиcано, что иcпользуетcя кодировка UTF-8, которая не поддерживает руccкий язык. Возможно я не прав, еще погуглю cей момент
