### ISSUE TITLE
Неполное отображение ника при наличие в нике двух или более слов 

### ISSUE THREAD

**Issue by ipehov** [maxkrivich/ChatApp#8]
Шаги по воспроизведению проблемы: 
1. Запустить программу
2. Ввести ник.
3. Подключиться к собеседнику, у которого ник состоит из двух или более слов (например ник "My Nick")

Ожидаемый результат:
Корректное отображение ника в поле Remote Login, то есть отображение ника полностью "My Nick"

Фактический результат:
Отображает только первое слово , например "My" из ника "My Nick" (В поле Remote Login и в оповещении о входящем соединении)

**Comment by entick** [comment]
Иcправил, вроде, да jar новый выложил
