### ISSUE TITLE
Еще один интересный баг)

### ISSUE THREAD

**Issue by ipehov** [maxkrivich/ChatApp#9]
Шаги по воспроизведению проблемы: 
1. Запустить программу
2. В поле ника нажать пробел и подтвердить (То есть пустой ник)
3. Подключиться к собеседнику. (Я подключался к себе, с другими скорее всего так же и будет)

Ожидаемый результат:
Запрос на соединение. 

Фактический результат:
Запроса нет.

В общем, если поставить такой ник, (который состоит только из пробела) то запроса на входящее соединение не будет. Будет просто на прямую коннектиться и даже не спрашивать разрешения у пользователя. Тестил только на себе, на других нету возможности

**Comment by entick** [comment]
Опишите подробнее ваши действия. К примеру, сейчас я зашел в программу, поставил пробел в поле ника, нажал аплай, и в подключение ввел адресс 127.0.0.1. Запрос пришел. Проблему не нашел. Может вы что-то не так делали?

**Comment by ipehov** [comment]
Не поленился записать
https://www.youtube.com/watch?v=WVE2TcA7jdo

**Comment by entick** [comment]
Доступ к просмотру видео ограничен

**Comment by ipehov** [comment]
Извиняюсь. 
https://www.youtube.com/watch?v=WVE2TcA7jdo

**Comment by entick** [comment]
Не поверите, делаю все тоже самое - все корректно работает. Что-бы разрешить ситуацию было принято решение "запретить" ники состоящие из пробелов, а так-же пробелы в начале ника. В дальнейшем если ники состоят из пробелов, они будут заменены на "unnamed", а пробелы в начале ника будут просто удаляться

**Comment by maxkrivich** [comment]
Тебе делать нечего? Сколько можно

**Comment by dimalit** [comment]
Ну чего - по-моему продуктивно.

**Comment by maxkrivich** [comment]
Пускай лучше чат педалит, а не писюльки пешет

**Comment by entick** [comment]
"Да не бомбит у меня". Он челоек балы зарабатывает. А мы на баги находим, ничего не делая, удобно. Лучше и не придумать.

**Comment by entick** [comment]
И вообще как ты хотел, если ты выложил релиз полный багов?

**Comment by maxkrivich** [comment]
Но не от одного человека же

**Comment by ipehov** [comment]
"Писюльки пешет"? Ты серьезно? 
Я типо тестер, ищу всякие баги и пытаюсь зарабатывать на этом баллы, чтобы было понятно еще и видео записал. А что мне делать не указывай, и со словами попроще будь, ок

**Comment by ipehov** [comment]
3 бага из 5, которые я расписал вы исправили, 2 остальные спорные. Или я здесь флуд развел по твоему, педальник ?

**Comment by maxkrivich** [comment]
Ой все

**Comment by entick** [comment]
Закрывай баги, которые мы исправили, пожалуйста, и со спорными чего там спорного тоже пиши. подробнее)

**Comment by maxkrivich** [comment]
Нужно вмонтировать защиту от ламеров, тест пускать перед открытиям чата)

**Comment by dimalit** [comment]
Закрывать, если что, может и владелец репо. Кстит, закрытые баги никуда не удаляются - так что потом при оценивании они OK видны.

**Comment by ipehov** [comment]
Парень, ты меня называешь ламером и не можешь этого обосновать. 
Посмотри как ведет себя твой напарник и как ведешь себя ты. 
Я расписал 5 проблем, к которым адекватно отнёсся твой друг и Дмитрий Николаевич в частности.
Я не хочу на Гитхабе, при нормальных людях, устраивать какой-то бред. Если у тебя какие-то проблемы, так может быть ты подойдешь ко мне и скажешь все это в лицо? И посмотрим какой ты герой.

**Comment by entick** [comment]
Да, но видите как оно бывает. У разработчиков работает, а вот у пользователей нет, хотя действия одинаковые. Но ориентация то идет на пользователей

**Comment by maxkrivich** [comment]
Чувак я не намикаю это просто шутка, не бомби )

**Comment by ipehov** [comment]
Крутая шутка, смешно

**Comment by maxkrivich** [comment]
Та ладно, не дуйся наша команда любит пользователе нашего чата) ☺
